export interface BalanceSheetEntry {
  "Treasury Shares Number": string;
  "Ordinary Shares Number": string;
  "Share Issued": string;
  "Net Debt": string;
  "Total Debt": string;
  "Tangible Book Value": string;
  "Invested Capital": string;
  "Working Capital": string;
  "Net Tangible Assets": string;
  "Capital Lease Obligations": string;
  "Common Stock Equity": string;
  "Total Capitalization": string;
  "Total Equity Gross Minority Interest": string;
  "Stockholders Equity": string;
  "Gains Losses Not Affecting Retained Earnings": string;
  "Other Equity Adjustments": string;
  "Treasury Stock": string;
  "Retained Earnings": string;
  "Additional Paid In Capital": string;
  "Capital Stock": string;
  "Common Stock": string;
  "Preferred Stock": string;
  "Total Liabilities Net Minority Interest": string;
  "Total Non Current Liabilities Net Minority Interest": string;
  "Other Non Current Liabilities": string;
  "Employee Benefits": string;
  "Tradeand Other Payables Non Current": string;
  "Non Current Deferred Liabilities": string;
  "Non Current Deferred Revenue": string;
  "Non Current Deferred Taxes Liabilities": string;
  "Long Term Debt And Capital Lease Obligation": string;
  "Long Term Capital Lease Obligation": string;
  "Long Term Debt": string;
  "Current Liabilities": string;
  "Other Current Liabilities": string;
  "Current Deferred Liabilities": string;
  "Current Deferred Revenue": string;
  "Current Debt And Capital Lease Obligation": string;
  "Current Capital Lease Obligation": string;
  "Current Debt": string;
  "Other Current Borrowings": string;
  "Current Provisions": string;
  "Payables And Accrued Expenses": string;
  "Current Accrued Expenses": string;
  "Interest Payable": string;
  "Payables": string;
  "Total Tax Payable": string;
  "Accounts Payable": string;
  "Total Assets": string;
  "Total Non Current Assets": string;
  "Other Non Current Assets": string;
  "Non Current Prepaid Assets": string;
  "Non Current Deferred Assets": string;
  "Non Current Deferred Taxes Assets": string;
  "Non Current Accounts Receivable": string;
  "Investments And Advances": string;
  "Other Investments": string;
  "Investmentin Financial Assets": string;
  "Available For Sale Securities": string;
  "Goodwill And Other Intangible Assets": string;
  "Other Intangible Assets": string;
  "Goodwill": string;
  "Net PPE": string;
  "Accumulated Depreciation": string;
  "Gross PPE": string;
  "Leases": string;
  "Construction In Progress": string;
  "Other Properties": string;
  "Machinery Furniture Equipment": string;
  "Buildings And Improvements": string;
  "Land And Improvements": string;
  "Properties": string;
  "Current Assets": string;
  "Other Current Assets": string;
  "Prepaid Assets": string;
  "Inventory": string;
  "Finished Goods": string;
  "Work In Process": string;
  "Raw Materials": string;
  "Receivables": string;
  "Accounts Receivable": string;
  "Allowance For Doubtful Accounts Receivable": string;
  "Gross Accounts Receivable": string;
  "Cash Cash Equivalents And Short Term Investments": string;
  "Other Short Term Investments": string;
  "Cash And Cash Equivalents": string;
  "year": string;
}