export interface CashFlowEntry {
  "Free Cash Flow": string;
  "Repurchase Of Capital Stock": string;
  "Repayment Of Debt": string;
  "Issuance Of Debt": string;
  "Capital Expenditure": string;
  "Interest Paid Supplemental Data": string;
  "Income Tax Paid Supplemental Data": string;
  "End Cash Position": string;
  "Beginning Cash Position": string;
  "Changes In Cash": string;
  "Financing Cash Flow": string;
  "Cash Flow From Continuing Financing Activities": string;
  "Net Other Financing Charges": string;
  "Proceeds From Stock Option Exercised": string;
  "Cash Dividends Paid": string;
  "Common Stock Dividend Paid": string;
  "Net Common Stock Issuance": string;
  "Common Stock Payments": string;
  "Net Issuance Payments Of Debt": string;
  "Net Long Term Debt Issuance": string;
  "Long Term Debt Payments": string;
  "Long Term Debt Issuance": string;
  "Investing Cash Flow": string;
  "Cash Flow From Continuing Investing Activities": string;
  "Net Other Investing Changes": string;
  "Net Investment Purchase And Sale": string;
  "Sale Of Investment": string;
  "Purchase Of Investment": string;
  "Net Business Purchase And Sale": string;
  "Purchase Of Business": string;
  "Net PPE Purchase And Sale": string;
  "Purchase Of PPE": string;
  "Capital Expenditure Reported": string;
  "Operating Cash Flow": string;
  "Cash Flow From Continuing Operating Activities": string;
  "Change In Working Capital": string;
  "Change In Other Working Capital": string;
  "Change In Other Current Liabilities": string;
  "Change In Payables And Accrued Expense": string;
  "Change In Accrued Expense": string;
  "Change In Payable": string;
  "Change In Account Payable": string;
  "Change In Prepaid Assets": string;
  "Change In Inventory": string;
  "Change In Receivables": string;
  "Changes In Account Receivables": string;
  "Other Non Cash Items": string;
  "Stock Based Compensation": string;
  "Deferred Tax": string;
  "Deferred Income Tax": string;
  "Depreciation Amortization Depletion": string;
  "Depreciation And Amortization": string;
  "Amortization Cash Flow": string;
  "Amortization Of Intangibles": string;
  "Depreciation": string;
  "Operating Gains Losses": string;
  "Gain Loss On Investment Securities": string;
  "Net Income From Continuing Operations": string;
  "year": string;
}
