export interface IncomeStatementEntry {
  "Tax Effect Of Unusual Items": string;
  "Tax Rate For Calcs": string;
  "Normalized EBITDA": string;
  "Total Unusual Items": string;
  "Total Unusual Items Excluding Goodwill": string;
  "Net Income From Continuing Operation Net Minority Interest": string;
  "Reconciled Depreciation": string;
  "Reconciled Cost Of Revenue": string;
  "EBITDA": string;
  "EBIT": string;
  "Net Interest Income": string;
  "Interest Expense": string;
  "Interest Income": string;
  "Normalized Income": string;
  "Net Income From Continuing And Discontinued Operation": string;
  "Total Expenses": string;
  "Total Operating Income As Reported": string;
  "Diluted Average Shares": string;
  "Basic Average Shares": string;
  "Diluted EPS": string;
  "Basic EPS": string;
  "Diluted NI Availto Com Stockholders": string;
  "Net Income Common Stockholders": string;
  "Net Income": string;
  "Net Income Including Noncontrolling Interests": string;
  "Net Income Continuous Operations": string;
  "Tax Provision": string;
  "Pretax Income": string;
  "Other Income Expense": string;
  "Other Non Operating Income Expenses": string;
  "Special Income Charges": string;
  "Restructuring And Mergern Acquisition": string;
  "Net Non Operating Interest Income Expense": string;
  "Interest Expense Non Operating": string;
  "Interest Income Non Operating": string;
  "Operating Income": string;
  "Operating Expense": string;
  "Research And Development": string;
  "Selling General And Administration": string;
  "Gross Profit": string;
  "Cost Of Revenue": string;
  "Total Revenue": string;
  "Operating Revenue": string;
  "year": string;
}
